### ISSUE TITLE
kmc_dump option ci and cx are reversed

### ISSUE THREAD

**Issue by yunesj** [marekkokot/KMC#5]
According to help:
```
-ci<value> - print k-mers occurring less than <value> times
-cx<value> - print k-mers occurring more of than <value> times
```
However, it seems like `-ci<value>` prints k-mers occuring **greater** than `<value>` times. Same for `-cx`.

**Comment by marekkokot** [comment]
Thanks,
more precisely -ci<value> prints k-mers occurring greater **or equal** to <value> times. To be consistent with kmc nad kmc_tools *print* was replaced with *exclude*.
