### ISSUE TITLE
Release 2.3 not tagged

### ISSUE THREAD

**Issue by Moisan** [marekkokot/KMC#7]
0635dae65d262fe8910a46bcf03c0f77c2801442 seems to be matching the release 2.3 which is [announced on the homepage](http://sun.aei.polsl.pl/REFRESH/index.php?page=projects&project=kmc&subpage=news) but is not available in the release section of the repository.

**Comment by marekkokot** [comment]
Done. Sorry for delay.

**Comment by Moisan** [comment]
Thanks!
